spring:
  datasource:
    url: jdbc:mysql://localhost:3306/YOUR_DB?characterEncoding=utf-8&cacheServerConfiguration=true&useLocalSessionState=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5

server:
  port: 8090
  servelet:
    session:
      timeout: 100
  tomcat:
    url-encoding: UTF-8


# mybatis.config= classpath:mybatis-config.xml
mybatis:
  mapperLocations: classpath:mappers/*.xml
  #domain object's package
  typeAliasesPackage: com.alany.spider.bean